// Hook installer: writes the bash forwarder + a single `hooks:` block to
// ~/.hermes/config.yaml. Both are previewable via IPC before the user
// confirms; the renderer renders the diff and shows the script verbatim.

import { ipcMain, app } from 'electron';
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync, chmodSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import YAML from 'yaml';

import { IPC, type HookInstallResult, type HookPreview } from './preload-api';
import { applyPatch, getSettings } from './settings-store';
import {
  hookListenerPort,
  isHookListenerRunning,
  startHookListener,
  stopHookListener,
} from './hook-listener';

const HOOK_NAMES = [
  'pre_llm_call',
  'post_llm_call',
  'pre_tool_call',
  'post_tool_call',
  'on_session_start',
  'on_session_end',
  'on_session_finalize',
  'on_session_reset',
  'subagent_stop',
] as const;

type HookName = (typeof HOOK_NAMES)[number];

function hermesHome(): string {
  if (process.env.HERMES_HOME) return process.env.HERMES_HOME;
  const fromSettings = getSettings().hermes.config_path;
  if (fromSettings && fromSettings.endsWith('config.yaml')) {
    return path.dirname(expand(fromSettings));
  }
  return path.join(os.homedir(), '.hermes');
}

function expand(p: string): string {
  if (p.startsWith('~')) return path.join(os.homedir(), p.slice(1));
  return p;
}

function configPath(): string {
  return path.join(hermesHome(), 'config.yaml');
}

function scriptPath(): string {
  return path.join(hermesHome(), 'hooks', 'hermes-faceplate-hook.sh');
}

function buildScript(port: number): string {
  // Single bash script. Hermes invokes us with the hook name as $1; we POST
  // the JSON payload (passed on stdin) to /hook/<name>. Always print `{}`
  // back to stdout per addendum #3 — observe-only, no rewrite.
  return `#!/usr/bin/env bash
# HermesAgent Faceplate hook bridge — auto-generated by ${app.getName()} v${app.getVersion()}.
# Forwards lifecycle payloads to the local Faceplate listener and returns
# an empty action object so hermes-agent's flow is undisturbed.

set -e
EVENT_NAME="\${1:-unknown}"
LISTENER_URL="http://127.0.0.1:${port}/hook/\${EVENT_NAME}"

# Read the JSON payload from stdin into a variable; cap at 256 KiB.
PAYLOAD=\$(head -c 262144)

# Best-effort POST. Curl errors are silently ignored — the agent must not be
# blocked on the Faceplate being up.
curl -fsS \\
  --max-time 1 \\
  -H 'content-type: application/json' \\
  -X POST "\${LISTENER_URL}" \\
  --data-binary "\${PAYLOAD}" >/dev/null 2>&1 || true

printf '{}'
`;
}

function buildHooksBlock(port: number): Record<HookName, string> {
  const sp = scriptPath();
  const block: Record<string, string> = {};
  for (const name of HOOK_NAMES) {
    block[name] = `${sp} ${name}`;
  }
  return block as Record<HookName, string>;
}

function readCurrentYaml(): string {
  const cp = configPath();
  if (!existsSync(cp)) return '';
  try {
    return readFileSync(cp, 'utf8');
  } catch {
    return '';
  }
}

function alreadyInstalled(currentYaml: string): boolean {
  if (!currentYaml) return false;
  // Cheap fingerprint — the auto-generated comment is unique to our installs.
  return currentYaml.includes('hermes-faceplate-hook.sh');
}

function mergedYaml(currentYaml: string, port: number): string {
  let doc: Record<string, unknown>;
  try {
    doc = (YAML.parse(currentYaml) ?? {}) as Record<string, unknown>;
  } catch {
    doc = {};
  }
  const ourBlock = buildHooksBlock(port);
  const existing = (doc.hooks ?? {}) as Record<string, unknown>;
  doc.hooks = { ...existing, ...ourBlock };
  return YAML.stringify(doc);
}

function strippedYaml(currentYaml: string): string {
  let doc: Record<string, unknown>;
  try {
    doc = (YAML.parse(currentYaml) ?? {}) as Record<string, unknown>;
  } catch {
    return currentYaml;
  }
  const hooks = (doc.hooks ?? {}) as Record<string, unknown>;
  for (const name of HOOK_NAMES) {
    const value = hooks[name];
    if (typeof value === 'string' && value.includes('hermes-faceplate-hook.sh')) {
      delete hooks[name];
    }
  }
  if (Object.keys(hooks).length === 0) delete doc.hooks;
  else doc.hooks = hooks;
  return YAML.stringify(doc);
}

function diffSummary(before: string, after: string): string {
  const beforeLines = new Set(before.split('\n'));
  const additions: string[] = [];
  for (const line of after.split('\n')) {
    if (!beforeLines.has(line) && line.trim().length > 0) {
      additions.push(`+ ${line}`);
    }
  }
  const removalsCandidate = new Set(after.split('\n'));
  const removals: string[] = [];
  for (const line of before.split('\n')) {
    if (!removalsCandidate.has(line) && line.trim().length > 0) {
      removals.push(`- ${line}`);
    }
  }
  return [...removals, ...additions].join('\n') || '(no changes)';
}

async function ensureListenerForPreview(): Promise<number> {
  if (!isHookListenerRunning()) {
    return startHookListener();
  }
  return hookListenerPort();
}

export async function previewHook(): Promise<HookPreview> {
  const port = await ensureListenerForPreview();
  const currentYaml = readCurrentYaml();
  const merged = mergedYaml(currentYaml, port);
  const script = buildScript(port);
  return {
    script_path: scriptPath(),
    script,
    config_path: configPath(),
    current_yaml: currentYaml,
    merged_yaml: merged,
    diff_summary: diffSummary(currentYaml, merged),
    already_installed: alreadyInstalled(currentYaml),
  };
}

function atomicWrite(targetPath: string, content: string, mode?: number): void {
  const dir = path.dirname(targetPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const tmp = `${targetPath}.faceplate.tmp`;
  writeFileSync(tmp, content, 'utf8');
  if (mode !== undefined) chmodSync(tmp, mode);
  renameSync(tmp, targetPath);
}

export async function installHook(): Promise<HookInstallResult> {
  try {
    const port = await ensureListenerForPreview();
    const sp = scriptPath();
    atomicWrite(sp, buildScript(port), 0o755);
    const cp = configPath();
    const merged = mergedYaml(readCurrentYaml(), port);
    atomicWrite(cp, merged);
    applyPatch({ hermes: { install_shell_hook: true } });
    return { ok: true, config_path: cp, script_path: sp, listener_port: port };
  } catch (err) {
    return {
      ok: false,
      config_path: configPath(),
      script_path: scriptPath(),
      listener_port: hookListenerPort(),
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export async function uninstallHook(): Promise<HookInstallResult> {
  try {
    const cp = configPath();
    if (existsSync(cp)) {
      const stripped = strippedYaml(readCurrentYaml());
      atomicWrite(cp, stripped);
    }
    // Leave the script on disk (harmless; user might want to re-enable
    // without re-running the install). The next install will overwrite it.
    applyPatch({ hermes: { install_shell_hook: false } });
    if (isHookListenerRunning()) await stopHookListener();
    return { ok: true, config_path: cp, script_path: scriptPath(), listener_port: 0 };
  } catch (err) {
    return {
      ok: false,
      config_path: configPath(),
      script_path: scriptPath(),
      listener_port: hookListenerPort(),
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export function registerHookIpc(): void {
  ipcMain.handle(IPC.hermes.hookPreview, () => previewHook());
  ipcMain.handle(IPC.hermes.hookInstall, () => installHook());
  ipcMain.handle(IPC.hermes.hookUninstall, () => uninstallHook());
}
