#!/usr/bin/env bash
# Install the Faceplate event-tap hook into a Hermes you run.
#
# Run this ON THE MACHINE WHERE HERMES RUNS. It writes a tiny forwarder
# script into ~/.hermes/hooks/ and registers it for every agent lifecycle
# event in ~/.hermes/config.yaml, so the Faceplate's avatar reacts to
# activity on every channel (CLI, Telegram, cron, …), not just its own
# chat window.
#
# Usage:
#   setup/hermes-event-hooks.sh [--callback-url URL] [--hermes-home DIR]
#
#   --callback-url URL  Where the Faceplate's hook listener is reachable.
#                       Default http://127.0.0.1:51789 (Faceplate on the
#                       same machine as Hermes). For a Faceplate on another
#                       machine, pass that machine's reachable address.
#   --hermes-home DIR   Hermes data dir (default $HERMES_HOME, else ~/.hermes).
#
# Re-running is safe: it never edits a config.yaml that already references
# the Faceplate hook.

set -euo pipefail

usage() { sed -n '2,20p' "$0" | sed 's/^#\{1,2\} \{0,1\}//'; }

callback="http://127.0.0.1:51789"
hermes_home="${HERMES_HOME:-$HOME/.hermes}"

while [ $# -gt 0 ]; do
  case "$1" in
    --callback-url) callback="${2:?--callback-url needs a value}"; shift 2 ;;
    --hermes-home)  hermes_home="${2:?--hermes-home needs a value}"; shift 2 ;;
    -h|--help)      usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

callback="${callback%/}"   # strip any trailing slash
hooks_dir="$hermes_home/hooks"
script_path="$hooks_dir/hermes-faceplate-hook.sh"
config="$hermes_home/config.yaml"

# Hermes lifecycle events the Faceplate listens for (mirrors hook-installer.ts).
HOOK_NAMES=(
  pre_llm_call post_llm_call pre_tool_call post_tool_call
  on_session_start on_session_end on_session_finalize on_session_reset
  subagent_stop
)

# ── write the forwarder script ───────────────────────────────────────────
mkdir -p "$hooks_dir"
cat > "$script_path" <<EOF
#!/usr/bin/env bash
# HermesAgent Faceplate hook bridge — auto-generated by hermes-event-hooks.sh.
# Forwards lifecycle payloads to the Faceplate's hook listener and returns
# an empty action object so hermes-agent's flow is undisturbed.
set -e
EVENT_NAME="\${1:-unknown}"
LISTENER_URL="$callback/hook/\${EVENT_NAME}"

# Read the JSON payload from stdin; cap at 256 KiB.
PAYLOAD=\$(head -c 262144)

# Best-effort POST. Curl errors are swallowed — the agent must never block
# on the Faceplate being up.
curl -fsS --max-time 1 \\
  -H 'content-type: application/json' \\
  -X POST "\${LISTENER_URL}" \\
  --data-binary "\${PAYLOAD}" >/dev/null 2>&1 || true

printf '{}'
EOF
chmod 755 "$script_path"
echo "✓ hook forwarder written → $script_path"

# ── register the hooks in config.yaml ────────────────────────────────────
block="hooks:"
for name in "${HOOK_NAMES[@]}"; do
  block="$block"$'\n'"  $name: $script_path $name"
done

if [ -f "$config" ] && grep -q 'hermes-faceplate-hook.sh' "$config"; then
  echo "· $config already references the Faceplate hook — left as-is"
elif [ ! -f "$config" ] || ! grep -qE '^hooks:' "$config"; then
  # No hooks: block yet — safe to append a fresh one.
  if [ -f "$config" ] && [ -s "$config" ] && [ -n "$(tail -c1 "$config")" ]; then
    printf '\n' >> "$config"
  fi
  printf '%s\n' "$block" >> "$config"
  echo "✓ hooks: block appended to $config"
else
  # A hooks: block already exists — don't risk corrupting hand-written YAML.
  echo
  echo "⚠ $config already has a 'hooks:' block. Add these lines under it:"
  echo
  for name in "${HOOK_NAMES[@]}"; do
    echo "  $name: $script_path $name"
  done
fi

echo
echo "Next: restart your Hermes gateway so it reloads config.yaml."
echo "The Faceplate's hook listener must be reachable at: $callback"
